name: Release Charts

on:
  push:
    branches:
      - master
    paths: 'charts/**'

jobs:
  helm-packaging:
    runs-on: ubuntu-latest
    steps:
      # full checkout for semantic-release
      - name: Full checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"